(ns brave-bot.op)

(def dispatch              0)
(def heartbeat             1)
(def identify              2)
(def status-update         3)
(def voice-state-update    4)
(def voice-server-ping     5)
(def resume                6)
(def reconnect             7)
(def request-guild-members 8)
(def invalid-session       9)
(def hello                10)
(def heartbeat-ack        11)
